CREATE TABLE oscar (
    MOV_ID integer REFERENCES movies (MOV_ID) ON DELETE CASCADE,
    OSC_FL character
);

CREATE TABLE imdb_rat (
    PROD_ID INTEGER REFERENCES prod (PROD_ID) ON DELETE CASCADE,
    RTNG numeric
);

CREATE TABLE movies (
    MOV_ID INTEGER PRIMARY KEY,
    MOV_NM  VARCHAR(512),
    CNTR VARCHAR(512),
    PROD_ID INTEGER REFERENCES prod (PROD_ID) ON DELETE CASCADE
);

CREATE TABLE prod (
    PROD_ID INTEGER PRIMARY KEY,
    PROD_NM VARCHAR(512)
);