CREATE TABLE movies (
    ID INTEGER PRIMARY KEY,
    MOV_NM  VARCHAR(512),
    CNTR VARCHAR(512),
    OSC_FL character
);

CREATE TABLE prod (
    ID INTEGER PRIMARY KEY,
    PROD_NM VARCHAR(512),
    RTNG numeric
);

CREATE TABLE PROD2MOV (
    MOV_ID REFERENCES movies (ID) ON DELETE CASCADE,
    PROD_ID REFERENCES prod (ID) ON DELETE CASCADE
    
);


